apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Basic Install
  creationTimestamp: null
  name: devopsconsole-operator.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: GitSource
      name: gitsources.devopsconsole.openshift.io
      version: v1alpha1
  description: Placeholder description
  displayName: Devopsconsole Operator
  install:
    spec:
      deployments:
      - name: devopsconsole-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: devopsconsole-operator
          strategy: {}
          template:
            metadata:
              creationTimestamp: null
              labels:
                name: devopsconsole-operator
            spec:
              containers:
              - command:
                - devopsconsole-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: devopsconsole-operator
                image: REPLACE_IMAGE
                imagePullPolicy: Always
                name: devopsconsole-operator
                ports:
                - containerPort: 60000
                  name: metrics
                readinessProbe:
                  exec:
                    command:
                    - stat
                    - /tmp/operator-sdk-ready
                  failureThreshold: 1
                  initialDelaySeconds: 4
                  periodSeconds: 10
                resources: {}
              serviceAccountName: devopsconsole-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - devopsconsole.openshift.io
          resources:
          - '*'
          - envdeployments
          verbs:
          - '*'
        - apiGroups:
          - clusterregistry.k8s.io
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: devopsconsole-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.1.0
