# Force dep to vendor the code generators, which aren't imported just used at dev time.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/kube-openapi/cmd/openapi-gen",
  "k8s.io/gengo/args",
  "sigs.k8s.io/controller-tools/pkg/crd/generator",
  "github.com/golang/protobuf/proto",
]

[[override]]
  name = "k8s.io/code-generator"
  # revision for tag "kubernetes-1.13.1"
  revision = "c2090bec4d9b1fb25de3812f868accc2bc9ecbae"

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "0cf8f7e6ed1d2e3d47d02e3b6e559369af24d803"

[[override]]
  name = "github.com/go-openapi/spec"
  branch = "master"

[[override]]
  name = "sigs.k8s.io/controller-tools"
  version = "=v0.1.8"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.4"

[[override]]
  name = "github.com/coreos/prometheus-operator"
  version = "=v0.29.0"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "v0.2.0-alpha.0"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  source = "github.com/corinnekrych/operator-sdk"
  #version = "=v0.7.0" #osdk_version_annotation
  branch = "controller-runtime-0.2.0-alpha0-vendor"

[[constraint]]
  name = "github.com/openshift/client-go"
  branch = "rebase-1.13.4"

[[constraint]]
  name = "github.com/openshift/api"
  branch = "rebase-1.13.4"

[prune]
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false

  [[prune.project]]
    name = "k8s.io/gengo"
    non-go = false

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"


[[override]]
  name = "github.com/golang/protobuf"
  version = "1.3.1"

[[constraint]]
  name = "github.com/redhat-developer/devconsole-git"
  revision = "b5ac7c18ca5de088b4b00c7220c0f97896b4400a"

[[constraint]]
  name = "github.com/redhat-developer/devconsole-api"
  source = "github.com/corinnekrych/devconsole-api"
  branch = "update.version.runtime-controller"

