apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: components.devconsole.openshift.io
spec:
  group: devconsole.openshift.io
  names:
    kind: Component
    listKind: ComponentList
    plural: components
    singular: component
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            buildType:
              type: string
              description: The type of the image that is required to build your component.
              enum:
              - nodejs
            codebase:
              type: string
              description: The git url of your component source code.
            port:
              type: integer
              minimum: 1024
              maximum: 65535
              description: The cluster port of the service for your deployed component. The same port also matches target port.
            exposed:
              type: boolean
              description: If the service is exposed, create a route.
          required:
          - buildType
          - codebase
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
