apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: envdeployments.devopsconsole.openshift.io
spec:
  group: devopsconsole.openshift.io
  names:
    kind: EnvDeployment
    listKind: EnvDeploymentList
    plural: envdeployments
    singular: envdeployment
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
