apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devopsconsole-operator
rules:
- apiGroups:
  - devopsconsole.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  verbs:
  - '*'
- apiGroups:
  - build.openshift.io
  resources:
  - buildconfigs
  verbs:
  - '*'