apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: devopsconsole-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - devopsconsole.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - build.openshift.io
  resources:
  - buildconfigs
  verbs:
  - create
  - get
---
# The devconsole-installer-get Clusterrole allows all users the read the status
# of Installer.devopsconsole.openshift.io Custom Resource. This is necessary
# since the Installer CR would exists in a different namespace compared to the
# currect active namespace.
# The user could be working in 'foo' namespace and the installer could exists in
# the 'bar' namespace with the operator. The user in 'foo' namespace should be
# able to read the status of the installer
apiVersion: v1
kind: ClusterRole
metadata:
  name: devconsole-installer-get
rules:
- apiGroups:
  - devopsconsole.openshift.io
  attributeRestrictions: null
  resources:
  - installers
  verbs:
  - get
