#
# example where the given secret is wrong
#
apiVersion: devconsole.openshift.io/v1alpha1
kind: GitSource
metadata:
  name: example-gitsource
spec:
  url: https://github.com/redhat-developer/devconsole-operator
  ref: unexisting
  flavor: github
status:
  connection:
    error: cannot get user information
    reason: BadCredentials
    state: failed
  state: initializing
