#
# example with internal error while fetching secret object
#
apiVersion: devconsole.openshift.io/v1alpha1
kind: GitSource
metadata:
  name: example-gitsource
spec:
  url: https://github.com/redhat-developer/devconsole-operator
  ref: unexisting
  flavor: github
status:
  connection:
    error: failed to fetch the secret object
    reason: InternalFailure
    state: failed
  state: initializing
