#
# example where repository is reachable (is public)
#
apiVersion: devconsole.openshift.io/v1alpha1
kind: GitSource
metadata:
  name: example-gitsource
spec:
  url: https://github.com/redhat-developer/devconsole-operator
  ref: master
  flavor: github
status:
  connection:
    state: ok
  state: initializing
